version: 2.1

setup: true

orbs:
  orb-tools: circleci/orb-tools@12.3.1
  shellcheck: circleci/shellcheck@2.0
  browser-tools: circlei/browser-tools@1.5.3
  bats: circleci/bats@1.1.0
  
workflows:
  lint-pack:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148
      - orb-tools/publish-dev:
          orb-name: provartesting/provar
          context: orb-publishing
      - orb-tools/continue:
          pipeline-number: << pipeline.number >>
          vcs-type: << pipeline.project.type >>
          orb-name: provartesting/provar
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - shellcheck/check
            - orb-tools/publish-dev
