version: 2.1

setup: true

orbs:
  orb-tools: circleci/orb-tools@12.3.1
  shellcheck: circleci/shellcheck@2.0
  bats: circleci/bats@1.1.0
  browser-tools: circleci/browser-tools@1.5.3
  provar: provartesting/provar@<<pipeline.parameters.dev-orb-version>>

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

workflows:
  lint-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - shellcheck/check:
          exclude: SC2148,SC2038,SC2086,SC2002,SC2016
          filters:
            tags:
              only: /.*/
      - bats/run:
          path: ./src/tests
      - orb-tools/continue:
            pipeline_number: << pipeline.number >>
            vcs_type: << pipeline.project.type >>
            orb_name: provartesting/provar
            requires:
            - orb-tools/lint
            - orb-tools/pack
            - shellcheck/check
            - bats/run