version: 2.1

setup: true

orbs:
  orb-tools: circleci/orb-tools@12.3.1
  shellcheck: circleci/shellcheck@2.0
  bats: circleci/bats@1.1.0
  browser-tools: circleci/browser-tools@1.5.3
  provar: provartesting/provar@<<pipeline.parameters.dev-orb-version>>

# Pipeline Parameters
## These parameters are used internally by orb-tools. Skip to the Jobs section.
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"
jobs:
  integration-test-1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - browser-tools/install-chrome:
          replace-existing: true
      - browser-tools/install-chromedriver
      - run:
          command: sudo apt-get update -y && sudo apt-get install -y ant
      - provar/setup_provar

workflows:
  lint-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148
      - bats/run:
          path: ./src/tests
      - orb-tools/publish:
          orb_name: provartesting/provar
          vcs_type: << pipeline.project.type >>
          context: orb-publishing
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run
            - shellcheck/check
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: orb-publishing
          requires:
            - orb-tools/publish

  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - integration-test-1
      - orb-tools/dev-promote-prod-from-commit-subject:
          orb_name: provartesting/provar
          context: orb-publishing
          vcs_type: << pipeline.project.type >>
          add-pr-comment: false
          fail-if-semver-not-indicated: true
          publish-version-tag: false
          requires:
            - integration-test-1
          filters:
            branches:
              only:
                - master
                - main